import type { SsrMovie } from "./ssrLibrary";

/**
 * Static fallback library embedded at build time.
 *
 * Guarantees that the SSR document ALWAYS carries a real poster library —
 * even when the Supabase query is slow/unreachable from the edge — so no-JS
 * TV browsers (pre-module Tizen/webOS) and crawlers never see an empty
 * "Loading…" shell. Interactive clients replace this with live data on boot.
 *
 * Refresh with: node scripts/refresh-ssr-snapshot.mjs
 */
const snap = (
  id: number,
  title: string,
  image: string,
  backdrop: string,
  genre: string[],
  year: number | null,
  rating: string | null,
  watchUrl: string,
): SsrMovie => ({ id, title, image, backdrop, genre, year, rating, watchUrl });

export const SSR_LIBRARY_SNAPSHOT: SsrMovie[] = [
  snap(
    5644,
    "365 Days to the Wedding - Episode 1",
    "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx165790-OwIZI9ArGR4Q.jpg",
    "https://s4.anilist.co/file/anilistcdn/media/anime/banner/165790-Ght1ChketFbS.jpg",
    ["Anime", "Romance", "Slice of Life"],
    2024,
    "TV-14",
    "https://nxsha.space/embed/tv/tt27497575/1/1?lang=hi&server=GbruHindi&one_server=true&disable_app_ad=true",
  ),
  snap(
    5645,
    "365 Days to the Wedding - Episode 2",
    "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx165790-OwIZI9ArGR4Q.jpg",
    "https://s4.anilist.co/file/anilistcdn/media/anime/banner/165790-Ght1ChketFbS.jpg",
    ["Anime", "Romance", "Slice of Life"],
    2024,
    "TV-14",
    "https://nxsha.space/embed/tv/tt27497575/1/2?lang=hi&server=GbruHindi&one_server=true&disable_app_ad=true",
  ),
  snap(
    5646,
    "365 Days to the Wedding - Episode 3",
    "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx165790-OwIZI9ArGR4Q.jpg",
    "https://s4.anilist.co/file/anilistcdn/media/anime/banner/165790-Ght1ChketFbS.jpg",
    ["Anime", "Romance", "Slice of Life"],
    2024,
    "TV-14",
    "https://nxsha.space/embed/tv/tt27497575/1/3?lang=hi&server=GbruHindi&one_server=true&disable_app_ad=true",
  ),
  snap(
    5647,
    "365 Days to the Wedding - Episode 4",
    "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx165790-OwIZI9ArGR4Q.jpg",
    "https://s4.anilist.co/file/anilistcdn/media/anime/banner/165790-Ght1ChketFbS.jpg",
    ["Anime", "Romance", "Slice of Life"],
    2024,
    "TV-14",
    "https://nxsha.space/embed/tv/tt27497575/1/4?lang=hi&server=GbruHindi&one_server=true&disable_app_ad=true",
  ),
  snap(
    5638,
    "ReLIFE: Final Arc - Episode 1",
    "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx98635-U7XClVuynqfY.png",
    "https://s4.anilist.co/file/anilistcdn/media/anime/banner/98635-NoUpOE940WyV.jpg",
    ["Anime", "Comedy", "Drama", "Romance", "Slice of Life"],
    2018,
    "TV-14",
    "https://nxsha.space/embed/tv/tt5857720/2/1?lang=hi&server=GbruHindi&one_server=true&disable_app_ad=true",
  ),
  snap(
    5639,
    "ReLIFE: Final Arc - Episode 2",
    "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx98635-U7XClVuynqfY.png",
    "https://s4.anilist.co/file/anilistcdn/media/anime/banner/98635-NoUpOE940WyV.jpg",
    ["Anime", "Comedy", "Drama", "Romance", "Slice of Life"],
    2018,
    "TV-14",
    "https://nxsha.space/embed/tv/tt5857720/2/2?lang=hi&server=GbruHindi&one_server=true&disable_app_ad=true",
  ),
  snap(
    5640,
    "ReLIFE: Final Arc - Episode 3",
    "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx98635-U7XClVuynqfY.png",
    "https://s4.anilist.co/file/anilistcdn/media/anime/banner/98635-NoUpOE940WyV.jpg",
    ["Anime", "Comedy", "Drama", "Romance", "Slice of Life"],
    2018,
    "TV-14",
    "https://nxsha.space/embed/tv/tt5857720/2/3?lang=hi&server=GbruHindi&one_server=true&disable_app_ad=true",
  ),
  snap(
    5642,
    "Shagahai ReLIFE Kenkyuujo Support-ka - Episode 1",
    "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/b108939-t99SwYtxtBuR.jpg",
    "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/b108939-t99SwYtxtBuR.jpg",
    ["Anime", "Slice of Life"],
    2018,
    "TV-14",
    "https://nxsha.space/embed/tv/tt5857720/3/1?lang=hi&server=GbruHindi&one_server=true&disable_app_ad=true",
  ),
  snap(
    5412,
    "The Angel Next Door Spoils Me Rotten - Meet the Angel",
    "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx143338-zhyDVYgEzsm5.png",
    "https://s4.anilist.co/file/anilistcdn/media/anime/banner/143338-d0AqJzRUQCgk.jpg",
    ["Anime", "Romance", "Slice of Life"],
    2023,
    "TV-14",
    "https://nxsha.space/embed/tv/tt19064770/1/1?lang=hi&server=GbruHindi&one_server=true&disable_app_ad=true",
  ),
  snap(
    5413,
    "The Angel Next Door Spoils Me Rotten - Dinner with the Angel",
    "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx143338-zhyDVYgEzsm5.png",
    "https://s4.anilist.co/file/anilistcdn/media/anime/banner/143338-d0AqJzRUQCgk.jpg",
    ["Anime", "Romance", "Slice of Life"],
    2023,
    "TV-14",
    "https://nxsha.space/embed/tv/tt19064770/1/2?lang=hi&server=GbruHindi&one_server=true&disable_app_ad=true",
  ),
  snap(
    5414,
    "The Angel Next Door Spoils Me Rotten - Reward for the Angel",
    "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx143338-zhyDVYgEzsm5.png",
    "https://s4.anilist.co/file/anilistcdn/media/anime/banner/143338-d0AqJzRUQCgk.jpg",
    ["Anime", "Romance", "Slice of Life"],
    2023,
    "TV-14",
    "https://nxsha.space/embed/tv/tt19064770/1/3?lang=hi&server=GbruHindi&one_server=true&disable_app_ad=true",
  ),
  snap(
    5453,
    "Kanojo, Okarishimasu Petit - Episode 6",
    "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/b123901-SE2GQngZ22fy.png",
    "https://s4.anilist.co/file/anilistcdn/media/anime/banner/123901-3FIrkDyJdTHT.jpg",
    ["Anime", "Comedy"],
    2020,
    "TV-14",
    "https://nxsha.space/embed/tv/tt11448214/2/6?lang=hi&server=GbruHindi&one_server=true&disable_app_ad=true",
  ),
  snap(
    5454,
    "Kanojo, Okarishimasu Petit - Episode 7",
    "https://s4.anilist.co/file/anilistcdn/media/anime/cover/medium/b123901-SE2GQngZ22fy.png",
    "https://s4.anilist.co/file/anilistcdn/media/anime/banner/123901-3FIrkDyJdTHT.jpg",
    ["Anime", "Comedy"],
    2020,
    "TV-14",
    "https://nxsha.space/embed/tv/tt11448214/2/7?lang=hi&server=GbruHindi&one_server=true&disable_app_ad=true",
  ),
  snap(
    5505,
    "Kanojo, Okarishimasu 2nd Season: Date Movie - Episode 3",
    "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx154176-f98GtCnYEAbY.jpg",
    "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx154176-f98GtCnYEAbY.jpg",
    ["Anime", "Comedy", "Romance", "Slice of Life"],
    2022,
    "TV-14",
    "https://nxsha.space/embed/tv/tt11448214/5/3?lang=hi&server=GbruHindi&one_server=true&disable_app_ad=true",
  ),
  snap(
    5506,
    "Kanojo, Okarishimasu 2nd Season: Date Movie - Episode 4",
    "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx154176-f98GtCnYEAbY.jpg",
    "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx154176-f98GtCnYEAbY.jpg",
    ["Anime", "Comedy", "Romance", "Slice of Life"],
    2022,
    "TV-14",
    "https://nxsha.space/embed/tv/tt11448214/5/4?lang=hi&server=GbruHindi&one_server=true&disable_app_ad=true",
  ),
  snap(
    3123,
    "Naruto: Shippuden - The Tenchi Bridge",
    "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1735-kGfVm0YqCPcu.png",
    "https://s4.anilist.co/file/anilistcdn/media/anime/banner/1735.jpg",
    ["Anime", "Action", "Adventure", "Comedy", "Drama", "Fantasy", "Supernatural"],
    2007,
    "TV-14",
    "https://nxsha.space/embed/tv/tt0988824/1/39?lang=hi&server=GbruHindi&one_server=true&disable_app_ad=true",
  ),
  snap(
    3124,
    "Naruto: Shippuden - The Nine-Tails Unleashed",
    "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1735-kGfVm0YqCPcu.png",
    "https://s4.anilist.co/file/anilistcdn/media/anime/banner/1735.jpg",
    ["Anime", "Action", "Adventure", "Comedy", "Drama", "Fantasy", "Supernatural"],
    2007,
    "TV-14",
    "https://nxsha.space/embed/tv/tt0988824/1/40?lang=hi&server=GbruHindi&one_server=true&disable_app_ad=true",
  ),
  snap(
    3125,
    "Naruto: Shippuden - The Top-Secret Mission Begins",
    "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1735-kGfVm0YqCPcu.png",
    "https://s4.anilist.co/file/anilistcdn/media/anime/banner/1735.jpg",
    ["Anime", "Action", "Adventure", "Comedy", "Drama", "Fantasy", "Supernatural"],
    2007,
    "TV-14",
    "https://nxsha.space/embed/tv/tt0988824/1/41?lang=hi&server=GbruHindi&one_server=true&disable_app_ad=true",
  ),
  snap(
    3126,
    "Naruto: Shippuden - Orochimaru vs. Jinchuriki",
    "https://s4.anilist.co/file/anilistcdn/media/anime/cover/large/bx1735-kGfVm0YqCPcu.png",
    "https://s4.anilist.co/file/anilistcdn/media/anime/banner/1735.jpg",
    ["Anime", "Action", "Adventure", "Comedy", "Drama", "Fantasy", "Supernatural"],
    2007,
    "TV-14",
    "https://nxsha.space/embed/tv/tt0988824/1/42?lang=hi&server=GbruHindi&one_server=true&disable_app_ad=true",
  ),
];
