/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiAnimeSeriesRouteImport } from './routes/api/anime-series'
import { Route as ApiAnimeRouteImport } from './routes/api/anime'

const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnimeSeriesRoute = ApiAnimeSeriesRouteImport.update({
  id: '/api/anime-series',
  path: '/api/anime-series',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnimeRoute = ApiAnimeRouteImport.update({
  id: '/api/anime',
  path: '/api/anime',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/anime': typeof ApiAnimeRoute
  '/api/anime-series': typeof ApiAnimeSeriesRoute
  '/api/auth': typeof ApiAuthRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/anime': typeof ApiAnimeRoute
  '/api/anime-series': typeof ApiAnimeSeriesRoute
  '/api/auth': typeof ApiAuthRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/anime': typeof ApiAnimeRoute
  '/api/anime-series': typeof ApiAnimeSeriesRoute
  '/api/auth': typeof ApiAuthRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/admin' | '/api/anime' | '/api/anime-series' | '/api/auth'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/admin' | '/api/anime' | '/api/anime-series' | '/api/auth'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/anime'
    | '/api/anime-series'
    | '/api/auth'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiAnimeRoute: typeof ApiAnimeRoute
  ApiAnimeSeriesRoute: typeof ApiAnimeSeriesRoute
  ApiAuthRoute: typeof ApiAuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anime-series': {
      id: '/api/anime-series'
      path: '/api/anime-series'
      fullPath: '/api/anime-series'
      preLoaderRoute: typeof ApiAnimeSeriesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anime': {
      id: '/api/anime'
      path: '/api/anime'
      fullPath: '/api/anime'
      preLoaderRoute: typeof ApiAnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiAnimeRoute: ApiAnimeRoute,
  ApiAnimeSeriesRoute: ApiAnimeSeriesRoute,
  ApiAuthRoute: ApiAuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
