/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as ApiAnimeRouteImport } from './routes/api/anime'
import { Route as ApiAnimeAutoRouteImport } from './routes/api/anime-auto'
import { Route as ApiAnimeSyncRouteImport } from './routes/api/anime-sync'
import { Route as ApiAnimeTrailerRouteImport } from './routes/api/anime-trailer'
import { Route as ApiAuthRouteImport } from './routes/api/auth'
import { Route as ApiConfigRouteImport } from './routes/api/config'
import { Route as ApiExtractRouteImport } from './routes/api/extract'
import { Route as ApiMoviesRouteImport } from './routes/api/movies'
import { Route as ApiNxshaFetchRouteImport } from './routes/api/nxsha-fetch'
import { Route as ApiPortraitPosterRouteImport } from './routes/api/portrait-poster'
import { Route as ApiStreamRouteImport } from './routes/api/stream'
import { Route as ApiSupabaseRouteImport } from './routes/api/supabase'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnimeRoute = ApiAnimeRouteImport.update({
  id: '/api/anime',
  path: '/api/anime',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnimeAutoRoute = ApiAnimeAutoRouteImport.update({
  id: '/api/anime-auto',
  path: '/api/anime-auto',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnimeSyncRoute = ApiAnimeSyncRouteImport.update({
  id: '/api/anime-sync',
  path: '/api/anime-sync',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAnimeTrailerRoute = ApiAnimeTrailerRouteImport.update({
  id: '/api/anime-trailer',
  path: '/api/anime-trailer',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthRoute = ApiAuthRouteImport.update({
  id: '/api/auth',
  path: '/api/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiConfigRoute = ApiConfigRouteImport.update({
  id: '/api/config',
  path: '/api/config',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiExtractRoute = ApiExtractRouteImport.update({
  id: '/api/extract',
  path: '/api/extract',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiMoviesRoute = ApiMoviesRouteImport.update({
  id: '/api/movies',
  path: '/api/movies',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiNxshaFetchRoute = ApiNxshaFetchRouteImport.update({
  id: '/api/nxsha-fetch',
  path: '/api/nxsha-fetch',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPortraitPosterRoute = ApiPortraitPosterRouteImport.update({
  id: '/api/portrait-poster',
  path: '/api/portrait-poster',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiStreamRoute = ApiStreamRouteImport.update({
  id: '/api/stream',
  path: '/api/stream',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiSupabaseRoute = ApiSupabaseRouteImport.update({
  id: '/api/supabase',
  path: '/api/supabase',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/anime': typeof ApiAnimeRoute
  '/api/anime-auto': typeof ApiAnimeAutoRoute
  '/api/anime-sync': typeof ApiAnimeSyncRoute
  '/api/anime-trailer': typeof ApiAnimeTrailerRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/config': typeof ApiConfigRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/movies': typeof ApiMoviesRoute
  '/api/nxsha-fetch': typeof ApiNxshaFetchRoute
  '/api/portrait-poster': typeof ApiPortraitPosterRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/supabase': typeof ApiSupabaseRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/anime': typeof ApiAnimeRoute
  '/api/anime-auto': typeof ApiAnimeAutoRoute
  '/api/anime-sync': typeof ApiAnimeSyncRoute
  '/api/anime-trailer': typeof ApiAnimeTrailerRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/config': typeof ApiConfigRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/movies': typeof ApiMoviesRoute
  '/api/nxsha-fetch': typeof ApiNxshaFetchRoute
  '/api/portrait-poster': typeof ApiPortraitPosterRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/supabase': typeof ApiSupabaseRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRoute
  '/api/anime': typeof ApiAnimeRoute
  '/api/anime-auto': typeof ApiAnimeAutoRoute
  '/api/anime-sync': typeof ApiAnimeSyncRoute
  '/api/anime-trailer': typeof ApiAnimeTrailerRoute
  '/api/auth': typeof ApiAuthRoute
  '/api/config': typeof ApiConfigRoute
  '/api/extract': typeof ApiExtractRoute
  '/api/movies': typeof ApiMoviesRoute
  '/api/nxsha-fetch': typeof ApiNxshaFetchRoute
  '/api/portrait-poster': typeof ApiPortraitPosterRoute
  '/api/stream': typeof ApiStreamRoute
  '/api/supabase': typeof ApiSupabaseRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/api/anime'
    | '/api/anime-auto'
    | '/api/anime-sync'
    | '/api/anime-trailer'
    | '/api/auth'
    | '/api/config'
    | '/api/extract'
    | '/api/movies'
    | '/api/nxsha-fetch'
    | '/api/portrait-poster'
    | '/api/stream'
    | '/api/supabase'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/api/anime'
    | '/api/anime-auto'
    | '/api/anime-sync'
    | '/api/anime-trailer'
    | '/api/auth'
    | '/api/config'
    | '/api/extract'
    | '/api/movies'
    | '/api/nxsha-fetch'
    | '/api/portrait-poster'
    | '/api/stream'
    | '/api/supabase'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/api/anime'
    | '/api/anime-auto'
    | '/api/anime-sync'
    | '/api/anime-trailer'
    | '/api/auth'
    | '/api/config'
    | '/api/extract'
    | '/api/movies'
    | '/api/nxsha-fetch'
    | '/api/portrait-poster'
    | '/api/stream'
    | '/api/supabase'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRoute
  ApiAnimeRoute: typeof ApiAnimeRoute
  ApiAnimeAutoRoute: typeof ApiAnimeAutoRoute
  ApiAnimeSyncRoute: typeof ApiAnimeSyncRoute
  ApiAnimeTrailerRoute: typeof ApiAnimeTrailerRoute
  ApiAuthRoute: typeof ApiAuthRoute
  ApiConfigRoute: typeof ApiConfigRoute
  ApiExtractRoute: typeof ApiExtractRoute
  ApiMoviesRoute: typeof ApiMoviesRoute
  ApiNxshaFetchRoute: typeof ApiNxshaFetchRoute
  ApiPortraitPosterRoute: typeof ApiPortraitPosterRoute
  ApiStreamRoute: typeof ApiStreamRoute
  ApiSupabaseRoute: typeof ApiSupabaseRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anime': {
      id: '/api/anime'
      path: '/api/anime'
      fullPath: '/api/anime'
      preLoaderRoute: typeof ApiAnimeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anime-auto': {
      id: '/api/anime-auto'
      path: '/api/anime-auto'
      fullPath: '/api/anime-auto'
      preLoaderRoute: typeof ApiAnimeAutoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anime-sync': {
      id: '/api/anime-sync'
      path: '/api/anime-sync'
      fullPath: '/api/anime-sync'
      preLoaderRoute: typeof ApiAnimeSyncRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/anime-trailer': {
      id: '/api/anime-trailer'
      path: '/api/anime-trailer'
      fullPath: '/api/anime-trailer'
      preLoaderRoute: typeof ApiAnimeTrailerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth': {
      id: '/api/auth'
      path: '/api/auth'
      fullPath: '/api/auth'
      preLoaderRoute: typeof ApiAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/config': {
      id: '/api/config'
      path: '/api/config'
      fullPath: '/api/config'
      preLoaderRoute: typeof ApiConfigRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/extract': {
      id: '/api/extract'
      path: '/api/extract'
      fullPath: '/api/extract'
      preLoaderRoute: typeof ApiExtractRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/movies': {
      id: '/api/movies'
      path: '/api/movies'
      fullPath: '/api/movies'
      preLoaderRoute: typeof ApiMoviesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/nxsha-fetch': {
      id: '/api/nxsha-fetch'
      path: '/api/nxsha-fetch'
      fullPath: '/api/nxsha-fetch'
      preLoaderRoute: typeof ApiNxshaFetchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/portrait-poster': {
      id: '/api/portrait-poster'
      path: '/api/portrait-poster'
      fullPath: '/api/portrait-poster'
      preLoaderRoute: typeof ApiPortraitPosterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/stream': {
      id: '/api/stream'
      path: '/api/stream'
      fullPath: '/api/stream'
      preLoaderRoute: typeof ApiStreamRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/supabase': {
      id: '/api/supabase'
      path: '/api/supabase'
      fullPath: '/api/supabase'
      preLoaderRoute: typeof ApiSupabaseRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRoute,
  ApiAnimeRoute: ApiAnimeRoute,
  ApiAnimeAutoRoute: ApiAnimeAutoRoute,
  ApiAnimeSyncRoute: ApiAnimeSyncRoute,
  ApiAnimeTrailerRoute: ApiAnimeTrailerRoute,
  ApiAuthRoute: ApiAuthRoute,
  ApiConfigRoute: ApiConfigRoute,
  ApiExtractRoute: ApiExtractRoute,
  ApiMoviesRoute: ApiMoviesRoute,
  ApiNxshaFetchRoute: ApiNxshaFetchRoute,
  ApiPortraitPosterRoute: ApiPortraitPosterRoute,
  ApiStreamRoute: ApiStreamRoute,
  ApiSupabaseRoute: ApiSupabaseRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
